#!/bin/bash
set -e

PY_FILE="${BASH_SOURCE[0]%.sh}.py"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
VENV_DIR="${SCRIPT_DIR}/.venv"

if [[ ! -d $VENV_DIR ]]
then
    >&2 echo ".venv not found. make sure to run poetry install --no-dev"
    exit 1
fi

$VENV_DIR/bin/python3.9 $PY_FILE $*